### ISSUE TITLE
doesn't work with keys

### ISSUE THREAD

**Issue by UziTech** [MohammadYounes/jquery-scrollLock#10]
PgUp, PgDn, arrow keys, spacebar all move the main scrollbar when the div's scrollbar reaches the end

**Comment by MohammadYounes** [comment]
Although this is intended to lock mouse wheel scroll inside a given container, but having an option to lock keys too would be an added value.

**Comment by MohammadYounes** [comment]
Does this happen in any none-webkit browser ?
