### ISSUE TITLE
seems not working on FireFox

### ISSUE THREAD

**Issue by yechongbo** [MohammadYounes/jquery-scrollLock#11]
I am using this lib to stop scroll propagation from a sidenav to its document body. Generally, it works very well except FireFox. And I also found that even the examples are not working very well on FireFox.

**Comment by MohammadYounes** [comment]
Can you provide an online sample ?

**Comment by yechongbo** [comment]
thanks for the reply. did you try the demo page at http://mohammadyounes.github.io/jquery-scrollLock/#demo , i believe it's not working very well on Firefox as well. thanks!

**Comment by MohammadYounes** [comment]
Yes, I tested it on Firefox 38/48 and everything seems fine.

**Comment by yechongbo** [comment]
[test.zip](https://github.com/MohammadYounes/jquery-scrollLock/files/484027/test.zip)

I uploaded a test to show my case, the problem happens when you keep scrolling even the scroll bar reaches the bottom in side nav. please help with this, thanks!

**Comment by MohammadYounes** [comment]
I don't see any problem with your demo. What is your OS/FF version ?

**Comment by yechongbo** [comment]
it's 48

**Comment by MohammadYounes** [comment]
What about OS ?

**Comment by yechongbo** [comment]
i am using a Mac, but it's the same in my Windows VM. Thanks for the help anyway, i am trying to get more details.

**Comment by yechongbo** [comment]
![image](https://cloud.githubusercontent.com/assets/11768463/18777013/8df8915c-819f-11e6-8fb6-2a327eb933e0.png)

I really don't know what's going on under the hook, but it does fix my issue after i added mousewheel event together with DOMMouseScroll. see the attached image.

**Comment by MohammadYounes** [comment]
Strange, FF does not support "mousehweel" event, instead it supports ["wheel"](https://developer.mozilla.org/en-US/docs/Web/Events/wheel) event.

Moreover,  Although ["DOMMouseScroll"](https://developer.mozilla.org/en-US/docs/Web/Events/DOMMouseScroll) is none-standard, But it is supported by FF. 



This is MDN recommendation for a [cross-browser mouse wheel event listener](https://developer.mozilla.org/en-US/docs/Web/Events/wheel#Listening_to_this_event_across_browser):

```js
// detect available wheel event
support = "onwheel" in document.createElement("div") ? "wheel" : // Modern browsers support "wheel"
          document.onmousewheel !== undefined ? "mousewheel" : // Webkit and IE support at least "mousewheel"
          "DOMMouseScroll"; // let's assume that remaining browsers are older Firefox
```
I have to check this on a mac and see what's going on.

Thanks!

**Comment by MohammadYounes** [comment]
Also check if you have any listener on `wheel` event that is calling `preventDefault()`.

According to [Gecko Notes](https://developer.mozilla.org/en-US/docs/Web/Events/wheel#Gecko_notes):

> If a trusted wheel event is not consumed, a DOMMouseScroll event and a MozMousePixelScroll event are fired for backward compatibility

So `DOMMouseScroll` will not fire if `preventDefault()` is called on a `wheel` event.

**Comment by yechongbo** [comment]
thanks man, i may know the cause, we are actually using jqueryCustomScroll and it seems to intercept the scroll event before your lib does. I just don't understand why it has problem on FireFox and just Firefox actually.

**Comment by MohammadYounes** [comment]
Backward compatibility, as FF will not fire the `DOMMouseScroll` if a `preventDefault()` is called on a `wheel` event.

**Comment by yechongbo** [comment]
oh i see, thanks

**Comment by MohammadYounes** [comment]
Wheel event detection updated according to MDN recommendation. Thanks!
