### ISSUE TITLE
Missing semicolon at end of file "jquery-scrollLock.js"

### ISSUE THREAD

**Issue by MiladSadinam** [MohammadYounes/jquery-scrollLock#12]
At the end of the file a semicolon is missing. I am using that file in my own minification process which causes an error then.

Would be grateful for a fix.

**Comment by MohammadYounes** [comment]
I am using [JavaScript Standard Style](http://standardjs.com/), thus [No Semicolons](http://standardjs.com/rules.html#semicolons). You'll face problems only if your next file starts with `(`, `[`, or `` ` ``. 

Can't you change the files order in your build process ?

**Comment by MiladSadinam** [comment]
Well I can do this. 

I just checked my libraries and most of them start with "("  (e.g. jquery or angularjs). So you would save the users of your library a lot of headache. Specially as it is pain in *** to find errors in minified/uglified code.
