### ISSUE TITLE
Unable to scroll child element when scrollLocked element is at top/bottom

### ISSUE THREAD

**Issue by ProdigySim** [MohammadYounes/jquery-scrollLock#13]
If I have a descendant div that is scrollable inside my scroll-locked element, I'm unable to scroll it up when the scroll-locked element is at its scroll-top. And conversely, when the scroll-locked element is at its scroll-bottom I am unable to scroll the descendant element down.

Demo: https://jsfiddle.net/04w558dw/

**Comment by ProdigySim** [comment]
This seems similar to #4 but in this case I don't want to scroll-lock the descendant element.

I don't know how to fix this issue other than recursively checking scroll properties and using [jQuery.fn.scrollParent()](https://api.jqueryui.com/scrollParent/) from `event.target` down to the scroll locked element.

**Comment by MohammadYounes** [comment]
Thanks for the details and the demo.

I think all you need to do is to stop wheel event propagation from the inner div:

```js 
$('.inner').on('wheel', function(e){e.stopPropagation();});
```

Does this fix your issue or I got it wrong?

**Comment by ProdigySim** [comment]
That fixes the issue, but creates another. If we `stopPropagation()` on the inner element, then it can be used to scroll elements outside of the `div.outer`.

For example, scroll down on this jsfiddle, then try to use the innermost element to scroll up:
https://jsfiddle.net/sovxr44d/

**Comment by MohammadYounes** [comment]
Looks like browser behavior is to fire a `scroll` event in this case, thus scrolling the parent container. 
https://jsfiddle.net/sovxr44d/1/

I'll need to investigate this more ...

**Comment by MohammadYounes** [comment]
@ProdigySim 

v3.1.0 introduces a new option to unblock scrollable children.

https://jsfiddle.net/sovxr44d/2/

Thanks!
