### ISSUE TITLE
Move minified files to dist subdirectory

### ISSUE THREAD

**Issue by chesio** [MohammadYounes/jquery-scrollLock#14]
Hi,

I have a small "feature" request. All of Bower packages I use have a `dist` subdirectory with minified version of the assets (be it CSS or JS). This makes it easy to deploy the package to production server as only contents of `dist` subdirectory has to be included. Would you consider adding `dist` subdirectory to your project and moving the minified assets there?

See [what-input](https://github.com/ten1seven/what-input) for an example of deploy-friendly file structure :-)

**Comment by MohammadYounes** [comment]
Hi,

I have no problem with having a `dist` folder, but wouldn't this affect existing users ?

You may also use [`bower-installer`](https://github.com/rquadling/bower-installer) to map the files to a custom destination. For example:

```json
{
  "dependencies": {
    "jquery-scrollLock": "^3.1.2"
  },
  "install": {
    "ignore": ["jquery"],
    "sources": {
      "jquery-scrollLock": {
        "mapping": [
          {
            "bower_components/jquery-scrollLock/jquery-scrollLock.min.js":
            "bower_components/jquery-scrollLock/dist/jquery-scrollLock.min.js"
          }
        ]
      }
    }
  }
}
```

The above `bower.json` will place `jquery-scrollLock.min.js` into `bower_components/jquery-scrollLock/dist` subdirectory.

**Comment by chesio** [comment]
> I have no problem with having a dist folder, but wouldn't this affect existing users ?

It certainly would, treat it just as a suggestion.

Thanks for the hint about `bower-installer`, I'll check it out!

**Comment by MohammadYounes** [comment]
As of 3.1.3 there is a copy of the minified files in a `dist` sub directory.

**Comment by chesio** [comment]
Thanks!
