### ISSUE TITLE
Package doesn't work with Disqus Widget

### ISSUE THREAD

**Issue by mho22** [MohammadYounes/jquery-scrollLock#18]
Hi all, 

I'm using your package and it is quite easy to make it work on any element.
But when it comes to add it to the Disqus Widget , no locks are generated : 

```
<div class="hidden-xs hidden-sm col-md-4">
        <!-- Disqus div -->
        <p id="hello" style="overflow-y: scroll; height:150px"  data-scrollLock>Lorem Ipsum</p>
        <div id="disqus_thread" data-scrollLock></div>
  </div>
```
```
<script>
        $(function ()
        {
            $('[data-scrollLock]').scrollLock();
        });
</script>
```

[https://demo.disqus.com/embed.js](url)

Here is the JS link.

It doesn't work for disqus_thread but it works perfectly for hello. 
I can't explain and find out the solution myself.

Thanks for your help

**Comment by MohammadYounes** [comment]
Hi,

This is because  `#disqus_thread` content is simply an IFRAME. Which will prevent scroll events from reaching the locked div.

Thanks.

**Comment by mho22** [comment]
Thanks for your answer,

I just want to find a solution about that. I was wondering if I set that scroll lock on a parent div it could be a solution but I found out that it wasn't. 
Do you think there is a solution or an alternative? 

Thanks

**Comment by MohammadYounes** [comment]
You have to access the IFRAME `contentDocument` and listen to the scroll event and pass it to the parent. I don't think it's possible in this specific case due to being a cross-origin frame and such access will be blocked.
