### ISSUE TITLE
Chrome Problem

### ISSUE THREAD

**Issue by fitzilla** [MohammadYounes/jquery-scrollLock#6]
Doesn't seem to work in Chrome v47.0. Scroll lock still scrolls beyond the div area when scrolling on my laptop trackpad.

**Comment by MohammadYounes** [comment]
I see no problem on Chrome 47! Are you using OSX ?

**Comment by fitzilla** [comment]
Hi Mohammad, Yes. OSX.

**Comment by MohammadYounes** [comment]
You might be having Show Scroll Bars set to When Scrolling in the General section of System Preferences ( see #3)

Try it with `force` options set to `true`.

**Comment by MohammadYounes** [comment]
duplicate #5
