### ISSUE TITLE
Doesn't work in mobile Safari or Chrome

### ISSUE THREAD

**Issue by tompazourek** [MohammadYounes/jquery-scrollLock#7]
This doesn't work in:

- Safari for iOS
- Chrome for iOS
- Chrome Device Emulator

In those, the enabled and disabled scroll lock make no difference.

I am guessing that it's because these have different way of scrolling, rather touch-based scrolling than mouse wheel scrolling.

Any ideas on how this can be solved? Are there some alternatives that work with both mouse wheel and touch? Or some complementary library that handles the touch input?

Thanks!

**Comment by MohammadYounes** [comment]
I haven't thought about touch scrolling before! and I'm not sure if touch events provide enough info to achieve the same behavior as mouse wheel events. I'll need to investigate this more (once I get some free time).

Thanks.

**Comment by MohammadYounes** [comment]
Touch support added in 2.1.0

**Comment by tompazourek** [comment]
Just tested on my iPhone in latest Safari and latest Chrome for iOS. It seems to work fine. I even tried it in the Chrome Device Emulator on my PC where it also works great.

Thanks a lot! :+1:
