### ISSUE TITLE
Add to npm registry

### ISSUE THREAD

**Issue by garethdn** [MohammadYounes/jquery-scrollLock#8]
Is there any chance of adding this library to npm package registry so that it can be added through package.json?

**Comment by MohammadYounes** [comment]
Sure, will do soon!

**Comment by MohammadYounes** [comment]
Added under https://www.npmjs.com/package/jquery-scroll-lock

Please check!

**Comment by lzilioli** [comment]
I don't think this package should be in the npm registry without a big giant warning at the top of the README that you are violating the GPL license simply by npm installing and using the package in your project.
