### ISSUE TITLE
Is it possible to disable scroll for middle mouse button and keyboard keys?

### ISSUE THREAD

**Issue by xstortionist** [MohammadYounes/jquery-scrollLock#9]
Is it possible to disable scroll for middle mouse button and keyboard keys?

**Comment by MohammadYounes** [comment]
I think this is outside the scope of this plugin. However, you can do this by preventing middle mouse button and up/down keys:

* Middle mouse button
```js
// disable middle mouse button
$('.scrollable').on('mousedown', function(e){ 
  if(e.button === 1)
    return false; 
});
```

* Up/Down Keys: 

```js
//disable up/down keys
$('.scrollable').on('keydown', function(e){ 
  if(e.keyCode == 38 || e.keyCode == 40) return false;
});
```
**Note** A scrollable element should be focusable to capture `keydown` event. An element such as `div` must have its tab index attribute set.

```html
<div tabindex="-1" style="outline:none;"> ... </div>
```
